<?php

defined('_JEXEC') or exit();

class helloworldViewItem extends JViewLegacy {

    protected $form;
    //protected $item;

    public function display($tpl = null)
    {
        $this->form = $this->get('Form');
        $this->item = $this->get('Item');
        $this->addToolBar();
        return parent::display($tpl); // TODO: Change the autogenerated stub
        $this->setDocument();
    }
    protected function addToolBar(){
        JToolbarHelper::title('Добавление нового');

        JToolbarHelper::save('item.save');
        JToolbarHelper::cancel('item.cancel');
    }
    protected function setDocument(){
        $document = JFactory::getDocument();
        $document->setTitle('Панель управления компонента новостей');
    }
}