<?php
defined('_JEXEC') or exit();

class helloworldViewItem extends JViewLegacy {
    protected $item;
    function display($tpl = null){
        $this->item = $this->get('Item');
        return parent::display($tpl); // TODO: Change the autogenerated stub
    }
}