<?php

defined('_JEXEC') or exit();

class helloworldViewhelloworld extends JViewLegacy {

    protected $items;
    protected $pagination;

    public function display($tpl = null){
        $this->items = $this->get('Items');
        $this->pagination = $this->get('Pagination');

        foreach ($this->items as $item){
            $item->images = json_decode($item->images);
        }
        $this->setDocument();
        return parent::display($tpl); // TODO: Change the autogenerated stub

    }
    protected function setDocument(){
        $document = JFactory::getDocument();

        $document->addStyleSheet(JUri::base().'components/com_helloworld/css/style.css');

    }
}